server:
  port: 2000
  servlet:
    context-path: /vision
spring:
  redis:
    database: 14
    host: 192.168.1.50
    port: 6379
    password: bizvane
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0
  swagger:
    show: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bizvane-test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*Mapper.xml

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
